title: "NuVizion IAM Portal"
description: "Sovereign Identity & Access Management for the NuVizion Ecosystem"
url: "https://nuvizion-society.github.io"
baseurl: "/IAM"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# NuVizion branding
organization: "NuVizion Universal Trust"
mission: "Revealing truth through sovereign research and cosmic archival"

# Navigation
header_pages:
  - about.md
  - chronicles.md
  - access.md
  - contact.md